name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v4
      - name: Set up python virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Update pip
        run: |
          python3 -m pip install --upgrade pip 'pip>=25.1.0'
      - name: Check Python version
        run: |
          python3 --version
          python3 -m pip list
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          skip_install: true
          plugin: clang-format
          gitref: main
          command: 'clang-format --version'
